Team-SSOK/ssok-backend

build.gradle
settings.gradle
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountException.java
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountExceptionHandler.java
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
ssok-common/build.gradle
ssok-common/src/main/java/kr/ssok/common/exception/BaseException.java
ssok-common/src/main/java/kr/ssok/common/exception/BaseResponse.java
ssok-common/src/main/java/kr/ssok/common/exception/BaseResponseStatus.java
ssok-common/src/main/java/kr/ssok/common/exception/CommonResponseStatus.java
ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java
ssok-common/src/main/java/kr/ssok/common/exception/ResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferException.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserException.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserExceptionHandler.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java

#8 
공통 모듈의 BaseResponse 관련 코드들을 추가, 수정했습니다.
각 서비스에 exception 관련 코드들을 생성해뒀습니다.

feat : common 모듈에 baseResponse,  jackson 의존성추가 (#8, SCRUM-114)

---

ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PinCodeRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/UserInfoResponseDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/ProfileImage.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/UserService.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

#30 
pin 번호 변경 요청 시 휴대폰 번호로 인증번호 발송 api
인증번호 인증 api
pin 번호 변경
내 프로필 유저 정보 조회 api
pin 번호 변경을 위해 핸드폰 인증에 완료하며 redis에 인증값을 true로 5분 저장해두었다가
이어서 유저가 pin번호를 입력하고 변경요청을 하면 redis에서 해당 인증값을 확인 후 pinCode를 암호화하여 update합니다.

feat: pin 재설정, 인증요청 / 유저 정보 조회 (#30, SCRUM-121)

---

ssok-transfer-service/.gitignore
ssok-transfer-service/build.gradle
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/QueryDSLConfig.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/TransferConfig.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferHistoryController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferCounterpartResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferHistoryRepository.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/TransferHistoryRepositoryCustom.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/impl/TransferHistoryRepositoryImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferHistoryService.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #28 close #29 
1. 최근 송금(출금)을 보낸 상대 계좌 목록을 조회 (입금 내역 x)
2. 중복된 상대 계좌는 제거되며, 가장 최근 송금 순으로 정렬되어 반환
3. 블루투스 송금에 대한 송금 계좌는 조회 x, 일반 송금에 대한 내역만 조회
4. 테스트 코드 작성(최신순, 중복 사용자 제거, 일반 송금만 처리, 출금 내역만 처리, 예외 처리)
- 추후 고려 사항
자주 확인하게 되는 내역이므로 캐싱이나 DB 인덱스 튜닝을 고려하면 좋겠다고 생각

feat/test: 최신 송금자 내역 조회 기능 및 테스트 (#28, SCRUM-62)

---

ssok-user-service/src/main/java/kr/ssok/userservice/controller/TermsController.java
ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/TermsDetailResponseDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/TermsListResponseDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/Terms.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
ssok-user-service/src/main/java/kr/ssok/userservice/repository/TermsRepository.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/TermsService.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/TermsServiceImpl.java

#32 
약관(terms) table, 약관 목록 조회, 약관 상세 조회 API
**추가 고려 사항**
약관 캐싱?

feat: 약관 목록 조회, 약관 상세 조회 API (#32, SCRUM-118)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/OpenBankingTransferRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java

close #35 
오픈뱅킹에 송금 요청 시, request dto에 입/출금 계좌의 예금주명 포함하도록 수정

feat: 오픈뱅킹에 송금 요청 시, 입/출금 계좌의 예금주명 포함하도록 수정 (#35, SCRUM-127)

---

ssok-user-service/build.gradle
ssok-user-service/src/main/java/kr/ssok/userservice/config/JpaAuditingConfig.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PhoneVerificationRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/PinCodeRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/SignupRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/BankAccountResponseDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
ssok-user-service/src/test/java/kr/ssok/userservice/config/TestAuditConfig.java
ssok-user-service/src/test/java/kr/ssok/userservice/config/TestSecurityConfig.java
ssok-user-service/src/test/java/kr/ssok/userservice/controller/TermsControllerTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/controller/UserControllerTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/entity/ProfileImageTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/entity/TermsTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/entity/UserTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/repository/TermsRepositoryTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/repository/UserRepositoryTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/service/impl/TermsServiceImplTest.java
ssok-user-service/src/test/java/kr/ssok/userservice/service/impl/UserServiceImplTest.java

#40 
UserServiceImpl 단위 테스트
UserController 단위 테스트
TermsService 단위 테스트
TermsController 단위 테스트
User, Terms, ProfileImage Entity 단위 테스트
UserRepository, TermsRepository 단위 테스트

test: user-service 계층 별 단위 테스트 (#40, SCRUM-123)

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/SsokBluetoothServiceApplication.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/UserServiceClient.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/AccountInfoDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/UserInfoDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/controller/BluetoothController.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/BluetoothMatchRequestDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/BluetoothMatchResponseDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/BluetoothService.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountIdResponse.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountIdsResponse.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/AccountResponse.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/OpenBankingTransferRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #50 close #51 
- 주변 기기의 Bluetooth UUID 기반 유저 정보 매칭
- 유저 이름 마스킹 처리
- 사용자 주 계좌 정보 조회
- 단위 테스트 작성
<br/>
- 추후 고려사항
- grpc 통신 변경
- 예외 처리 세분화

feat/test: uuid 리스트로 user 정보 조회 및 사용자 주계좌 조회 (#50, SCRUM-126)

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/AccountInfoDto.java
ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/request/OpenBankingTransferRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdsResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/PrimaryAccountResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/BluetoothTransferRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/BluetoothTransferResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferService.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #53 close #56 
- 블루투스 송금
- 출금 계좌(본인 주 계좌)와 입금 계좌(상대 주 계좌)에 대한 정보, 은행 코드로 송금 요청
- 계좌 id로 본인 계좌, 상대 계좌 번호를 조회하고 계좌 번호와 은행 코드로 오픈 뱅킹에 요청
- 송금 금액으로 입/출금 진행

feat/test/refactor: 블루투스 송금 기능 (#53, SCRUM-148)

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothExceptionHandler.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/OpenBankingResponse.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/FeignClientDecoderConfig.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/TransferRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/feign/FeignClientGlobalErrorDecoder.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #59 
- open feign 통신을 사용하는 오픈뱅킹 송금 요청에 대한 에러 응답 처리

feat: 오픈뱅킹 통신 에러처리 (#59, SCRUM-134)

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/BluetoothMatchResponseDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/UserInfoResponseDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java

close #62 
- user-bluetooth openfeign dto 변경

fix: user-bluetooth openfeign dto 변경 (#62, SCRUM-154)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/client/UserServiceClient.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java

close #65 
- 유저 서비스 - 계좌 서비스 통신 URL 수정
👍

fix: 유저 서비스 - 계좌 서비스 통신 URL 수정 (#65, SCRUM-156)

---

settings.gradle
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/config/SwaggerConfig.java
ssok-transfer-service/build.gradle
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/SwaggerConfig.java

close #64 
- 블루투스, 송금 서비스 스웨거 추가

feat: 블루투스, 송금 서비스 스웨거 추가 (#64, SCRUM-155)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java

hotfix: 계좌 - 송금 서비스 간의 URL 수정

---

docker-compose.yml
ssok-account-service/src/main/java/kr/ssok/accountservice/config/SwaggerConfig.java
ssok-user-service/src/main/java/kr/ssok/userservice/config/SecurityConfig.java
ssok-user-service/src/main/java/kr/ssok/userservice/config/SwaggerConfig.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
ssok-user-service/src/main/java/kr/ssok/userservice/repository/ProfileImageRepository.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

#70 
hotfix  msa 통합 테스트 중 수정사항 반영

Hotfix : msa 통합 테스트 중 수정사항 반영

---

ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/PrimaryAccountInfoResponseDto.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountInternalService.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImplTest.java

close #69 
- 주 계좌 정보 조회 기능 REST API 개발, 테스트, 예외 처리
- MSA 내부의 송금 서버가 해당 기능 요청 시, DB로 부터 해당 데이터 조회
- 이후, 조회 결과를 송금 서버로 전달
**차후 고려 대상:**
- 해당 부분을 gRPC로 리팩토링할 예정
- 송금 서버와의 통합 테스트 예정
- 예외 처리 코드 다시 확인 예정
😮😮😮

주 계좌 정보 조회 기능 (송금 서버 연동) 구현 (#69. SCRUM-159)

---

Jenkinsfile
build.gradle

#58 
jenkinsfile 생성 및 남아있던 config 관련 build 삭제

fix : jenkinsfile feature, 남아있던 config 관련 build 삭제

---

Jenkinsfile

jenkins build test 중
- cleanWs() 로 수정

fix : jenkinsfile celanWs() 로 수정

---

ssok-common/build.gradle
ssok-gateway/build.gradle

fix : dependency
lombok, web - webflux 충돌 ..

fix : dependency

---

Jenkinsfile

#58 
fix : common 변경사항 있을 시 common도 재 빌드

fix : common 변경사항 있을 시 common도 재 빌드

---

Jenkinsfile

#58 
fix : common 변경사항 있을 시 common도 재 빌드

fix : common 변경사항 있을 시 common도 재 빌드 + 디테일 추가

---

Jenkinsfile

#58 
fix : common 변경사항 있을 시 common도 재 빌드 - cleanWs 주석

fix : common 변경사항 있을 시 common도 재 빌드 - cleanWs 주석

---

Jenkinsfile

#58 
test : jenkinsfile git pull 제거 build test

test : jenkinsfile git pull 제거 build test

---

Jenkinsfile

#58 
test : jenkins ci 시작 시에 cleanWs() 추가3

test : jenkins ci 시작 시에 cleanWs() 추가3

---

Jenkinsfile

#58 
test : jenkins ci 끝나고 cleanWs() 추가4

test : jenkins ci 끝나고 cleanWs() 추가4

---

Jenkinsfile

test : jenkins build test

---

Jenkinsfile
ssok-account-service/Dockerfile
ssok-bluetooth-service/Dockerfile
ssok-common/build.gradle
ssok-common/src/main/java/kr/ssok/common/exception/CommonResponseStatus.java
ssok-gateway/Dockerfile
ssok-notification-service/Dockerfile
ssok-transfer-service/Dockerfile
ssok-user-service/Dockerfile

#58 
test : 공용모듈 빌드 의존성 문제 해결 시도

test : 공용모듈 빌드 의존성 문제 해결 시도

---

JenkinsfileBackUp

#58 
test : target jar -> docker image build 방식으로 변경

test : target jar -> docker image build 방식으로 변경

---

ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java

#58 
test : target jar -> docker image build 방식으로 변경 - build test

test : target jar -> docker image build 방식으로 변경 - build test

---

ssok-common/src/main/java/kr/ssok/common/exception/ExceptionHandler.java

test : argroCD 동작 test

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
ssok-notification-service/.gitignore
ssok-notification-service/build.gradle
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/controller/AligoController.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/dto/AligoVerificationRequestDto.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/service/AligoService.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/client/FirebaseClient.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/FirebaseConfig.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/RedisConfig.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/SwaggerConfig.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/controller/FcmController.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/request/FcmMessageRequestDto.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/dto/request/FcmRegisterRequestDto.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/FcmService.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/FcmServiceImpl.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/NotificationServiceImpl.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/NotificationService.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationException.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationExceptionHandler.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/AccountIdResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/TransferHistory.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #75 
- FCM 설정
- FCM 토큰 redis 등록
- FCM 토큰으로 FCM에 푸시 알림 요청
- 송금 - 계좌 서비스 응답 dto 수정
<br/>
- 추가할 것
- kafka로 송금 - 알림 서비스 이벤트 환경 구축

feat: 푸시 알림 기능 (#75, SCRUM-161)

---

Jenkinsfile

#58 
fix : jenkinsfile에 firebase sdk 추가

fix : jenkinsfile에 firebase sdk 추가

---

Jenkinsfile

#58 
[fix : jenkinsfile gateway -> gateway-service](https://github.com/Team-SSOK/ssok-backend/commit/07fa7b468f5d50f163e20468767cab6813ceeccc)

fix : jenkinsfile gateway -> gateway-service

---

Jenkinsfile
build.gradle
ssok-gateway-service/src/main/java/kr/ssok/gateway/SsokGatewayApplication.java
ssok-gateway-service/src/main/java/kr/ssok/gateway/config/RedisConfig.java
ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java
ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java
ssok-gateway-service/src/main/java/kr/ssok/gateway/security/handler/JwtAuthenticationEntryPoint.java
ssok-gateway-service/src/main/java/kr/ssok/gateway/security/jwt/JwtVerifier.java
ssok-gateway-service/src/test/java/kr/ssok/gateway/SsokGatewayApplicationTests.java

#58 
fix : ssok-gateway -> ssok-gateway-service
모듈명따라 gradle 빌드로 jar 파일이 생성되는 것을 확인.
모듈 명을 gateway-service로 변경. ssok-deploy 내용과 일치시킴

fix : ssok-gateway -> ssok-gateway-service

---

ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java

…입 방식으로 변경 (완전삭제)
#58 
fix : kubernetes config, yml 변환 시 복수 value 파싱 문제로 whitelist 코드단에 직접 주입 방식으로 변경 (완전삭제)

fix : kubernetes config, yml 변환 시 복수 value 파싱 문제로 whitelist 코드단에 직접 주입 방식으로 변경 (완전삭제)

---

ssok-gateway-service/src/main/java/kr/ssok/gateway/security/filter/JwtAuthenticationFilter.java

#58 
fix : kubernetes config, yml 변환 시 복수 value 파싱 문제로 whitelist 코드단에 직접 주입 방식으로 변경
JwtAuthenticationFilter 부분 추가 수정

fix : kubernetes config yml / JwtAuthenticationFilter 부분 추가 수정

---

ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
ssok-account-service/src/main/java/kr/ssok/accountservice/client/dto/response/OpenBankingResponse.java
ssok-account-service/src/main/java/kr/ssok/accountservice/config/FeignClientDecoderConfig.java
ssok-account-service/src/main/java/kr/ssok/accountservice/config/JpaAuditingConfig.java
ssok-account-service/src/main/java/kr/ssok/accountservice/config/SwaggerConfig.java
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/feign/FeignClientGlobalErrorDecoder.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java

close #107 
- 오픈뱅킹 에러에 대한 예외처리 추가

refactor: 오픈뱅킹 서버 API 요청에 대한 에러 응답 처리 (#107, SCRUM-153)

---

settings.gradle

#61 
jakartaAnnotation 버전이 낮은 버전(1.3.5)로 주입되어있었음.
컴파일 에러가 나와서 버전 수정

fix : jakartaAnnotation 버전 up!

---

ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

fix : 회원가입 api에 bank service랑 연동 주석 제거

fix : 회원가입 api에 bank service랑 연동 주석 제거

---

ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/BankAccountRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

#123
연동api 뱅크서버 계좌생성에 userTypeCode 추가 (#123/SCRUM-168)
bank server api 명세서에 누락된 request 값 확인.
추가 후 push.

fix : 연동api 뱅크서버 계좌생성에 userTypeCode 추가 (#123/SCRUM-168)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImpl.java
ssok-account-service/src/test/java/kr/ssok/accountservice/service/impl/AccountOpenBankingServiceImplTest.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #122 
- transfer service 서버에서 오픈뱅킹 요청 헤더에 API-KEY 추가
- account service 서버에서 오픈뱅킹 요청 헤더에 API-KEY 추가
🎶🎶

refactor: 오픈뱅킹 요청 로직 헤더에 API 키 추가 (#122, SCRUM-167)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java
ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountOpenBankingController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java

close #126 
- 계좌 서버, 컨트롤러 URL 변경
- 송금 서버, FiegnClient URL 변경
😄😄😄😄

refactor: 계좌 서버 외부 호출용 API URL 변경 (#126, SCRUM-170)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #132 
블루투스 송금 푸시알림 kafka 적용 & 테스트 코드 수정

fix: 블루투스 송금 푸시알림 kafka 적용 & 테스트 코드 수정 (#132, SCRUM-164)

---

ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

fix : accountTypeCode 1 -> 0 (적금 -> 예금)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/OpenBankingClient.java

fix: 오픈 뱅킹 송금 요청 api url 수정 (#134, SCRUM-172)

---

ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/SignupRequestDto.java

fix : 회원가입시 전화번호 정규식 수정

---

ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
ssok-account-service/src/main/java/kr/ssok/accountservice/exception/AccountResponseStatus.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/AccountServiceClient.java

close #146 
- 계좌 서버 컨트롤러 수정
- 송금 서버 클라이언트 수정
- 블루투스 서버 클라이언트 수정
📌

fix: 주 계좌 정보 조회 코드 오류 수정 (내부 서버 연동 API) (#146, SCRUM-180)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/controller/AccountInternalController.java
ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/bluetoothservice/PrimaryAccountBalanceResponseDto.java
ssok-account-service/src/main/java/kr/ssok/accountservice/dto/response/transferservice/PrimaryAccountInfoResponseDto.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/AccountInternalService.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountInternalServiceImpl.java
ssok-account-service/src/main/java/kr/ssok/accountservice/service/impl/AccountServiceImpl.java

close #148 
- 주계좌 잔액 조회 기능 추기
- 주계좌 정보 조회 기능 수정
🫠

fix: 주 계좌 정보 조회 코드 오류 추가 수정 (내부 서버 연동 API) (#148, SCRUM-180)

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/dto/response/PrimaryAccountResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/feign/FeignClientGlobalErrorDecoder.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #134
- 블루투스 서비스 - 계좌 서비스 openfeign dto 수정
- 테스트 코드 수정
- 오픈 뱅킹 예외처리 수정

fix: 블루투스 서비스 / 송금 서비스 수정

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferHistoryController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferRecentHistoryResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferExceptionHandler.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/TransferHistoryRepository.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferHistoryService.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferHistoryServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java

close #151 close #152 
- 최근 송금 내역 조회 기능
- 테스트 코드

feat/test: 최근 송금 내역 조회 기능 & 테스트 코드 (#151#152, SCRUM-183)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/request/TransferBluetoothRequestDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java

close #154
- 블루투스 송금 내역 저장 문제 수정

fix: 블루투스 송금 내역 저장 문제 수정 (#154, SCRUM-184)

---

ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/enums/BankCode.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/message/NotificationConsumer.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/FcmServiceImpl.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/service/Impl/NotificationServiceImpl.java

close #159 
- redis fcm key 식별 에러 수정
- 푸시알림 body 수정 (은행명 추가)

hotfix: redis fcm key 식별 에러 수정 & 푸시알림 body 수정(#159, SCRUM-190)

---

ssok-common/build.gradle

test : 전체 재 빌드

---

ssok-user-service/src/main/java/kr/ssok/userservice/config/S3Config.java

fix : aws s3 value 기본값 추가

---

ssok-gateway-service/src/main/java/kr/ssok/gateway/config/SecurityConfig.java

close #174
- prometheus 경로 추가
- /actuator/prometheus 추가

feat: prometheus 경로 추가 (#174, SCRUM-198)

---

ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/opensearch/controller/TestAlertController.java

close #177 
- opensearch alert test api 개발

test: opensearch alert test api 개발 (#177, SCRUM-214)

---

ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/ProfileServiceImpl.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

fix : S3 기본 파일(noImage) 관련 누락 수정

---

ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/TransferServiceClient.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/client/dto/UserInfoDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/controller/TransferController.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/BluetoothTransferRequestDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/request/TransferRequestDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/BluetoothTransferResponseDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/dto/response/UserInfoResponseDto.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/exception/BluetoothResponseStatus.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/TransferService.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/BluetoothServiceImpl.java
ssok-bluetooth-service/src/main/java/kr/ssok/bluetoothservice/service/impl/TransferServiceImpl.java
ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/BluetoothServiceTest.java
ssok-bluetooth-service/src/test/java/kr/ssok/bluetoothservice/service/TransferServiceImplTest.java

close #158 close #190 
- bluetooth uuid 매칭 유저 정보 리팽토링
- 위의 수정사항에 맞게 블루투스 송금 로직 변경

refactor/test: 블루투스 송금 로직 및 매칭 유저 정보 조회 리팩토링 & 테스트 코드 작성 (#158 #190, SCRUM-187)

---

ssok-account-service/src/main/java/kr/ssok/accountservice/client/OpenBankingClient.java

close #192 
- feign client 코드에서 GET -> POST로 수정
😥😥

fix: 오픈뱅킹 잔액 조회 요청 기능 수정 (#192, SCRUM-240)

---

ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/controller/FcmController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/enums/BankCode.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/helper/TransferNotificationSender.java

#196 
- 송금 시, 알림 kafka fallback 처리 (kafka connect 실패 -> openfeign 적용)

feat: 송금 시, 알림 kafka fallback 처리 (#196, SCURM-244)

---

ssok-user-service/src/main/java/kr/ssok/userservice/controller/UserController.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/CompleteSignupRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/request/ReRegisterPinRequestDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/dto/response/PhoneVerificationResponseDto.java
ssok-user-service/src/main/java/kr/ssok/userservice/entity/User.java
ssok-user-service/src/main/java/kr/ssok/userservice/exception/UserResponseStatus.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/UserService.java
ssok-user-service/src/main/java/kr/ssok/userservice/service/impl/UserServiceImpl.java

#223 
- 회원가입 API 개선: 휴대폰 인증 완료 상태 확인 후 처리
- 휴대폰 인증 API 개선: 기존 사용자 여부 확인 및 상태 관리
- PIN 재등록 기능 완성: 기존 사용자용 PIN 재등록 API 추가
- Redis 기반 인증 상태 관리: TTL 설정으로 보안 강화
- 새로운 에러 상태 추가: PHONE_VERIFICATION_REQUIRED

feat: 휴대폰 인증 기반 회원가입 및 PIN 재등록 로직 개선

---

ssok-gateway-service/build.gradle

#223 
hotfix : gateway grpc 의존성 누락

hotfix : gateway grpc 의존성 누락

---

ssok-gateway-service/build.gradle

hotfix : gateway grpc 의존성 충돌

---

ssok-transfer-service/build.gradle

hotfix: gRPC 도입 후, transfer 서버 에러 수정

---

ssok-transfer-service/build.gradle

fix: transfer service gradle 추가 수정

---

ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/controller/AligoController.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/aligo/service/AligoService.java

fix : aligo testmode 제거

---

ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/client/FirebaseClient.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/config/KafkaConsumerConfig.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/kafka/consumer/NotificationConsumer.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/domain/fcm/kafka/handler/KafkaDltHandler.java
ssok-notification-service/src/main/java/kr/ssok/notificationservice/global/exception/NotificationResponseStatus.java

close #245 
- kafka fcm exception swallow 문제 해결

hotfix: kafka fcm exception swallow 문제 해결(#243, SCRUM-281)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/grpc/client/AccountService.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/grpc/client/AccountServiceClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

#243 
- account service grpc method 명 수정

fix: account service grpc method 수정 (#243, SCRUM-281)

---

ssok-transfer-service/src/main/java/kr/ssok/transferservice/dto/response/TransferCounterpartResponseDto.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/entity/TransferHistory.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/repository/custom/impl/TransferHistoryRepositoryImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/helper/TransferHistoryRecorder.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferHistoryServiceTest.java

close #254 
- 최신 송금자 조회시, 뱅크 코드 추가

feat: 최신 송금자 조회시, 뱅크 코드 추가 (#254, SCRUM-287)

---

ssok-transfer-service/build.gradle
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/webclient/OpenBankingApiClient.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/client/webclient/impl/OpenBankingApiClientImpl.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/AsyncConfig.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/config/WebClientConfig.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/controller/TransferController.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/exception/TransferResponseStatus.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/TransferService.java
ssok-transfer-service/src/main/java/kr/ssok/transferservice/service/impl/TransferServiceImpl.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/repository/TransferHistoryRepositoryTest.java
ssok-transfer-service/src/test/java/kr/ssok/transferservice/service/TransferServiceTest.java

close #222 
- 오픈뱅킹 송금 요청을 비동기 논블락킹 방식으로 개성 -> webclient & completablefutrue 적용
- 테스트 코드 수정

refactor: 송금 서비스 오픈 뱅킹 요청 webclient 적용 (#222, SCRUM-280)
